name: Build Image in ACR
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR Build
        uses: azure/acr-build@v1
        with:
          registry: DotnetWeb
          repository: DotnetWeb
          image: test:v1
          tenant: ${{ secrets.AZURE_TENANT }}
          branch: main
          service_principal: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
